void write_Comand(unsigned char *);
void dfplayer_pista(unsigned char);
void dfplayer_Pause(void);
void dfplayer_Play(void);
void dfplayer_Next(void);
void dfplayer_Prev(void);
void dfplayer_Volume(unsigned char);
void dfplayer_Volume_up(void);
void dfplayer_Volume_down(void);
void reproduccion_pista(int, int);